#!/usr/bin/env bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "${DIR}/lib.sh"

cat <<EOF
---------------------------------------------------------
Starting test: node
IMAGE: ${IMAGE}
---------------------------------------------------------
EOF

MASTER=memsql-node-ma
LEAF=memsql-node-leaf

create-node ${MASTER}
create-node ${LEAF}
wait-start ${MASTER}
wait-start ${LEAF}

assert-memsqld-running ${MASTER}
assert-memsqld-running ${LEAF}

echo "testing that pre-start-success exists"
run ${MASTER} test -f /tmp/pre-start-success

bootstrap ${MASTER}
add-leaf ${MASTER} ${LEAF}

memsql-init-data ${MASTER}
memsql-verify-data ${MASTER}

# verify the data is a-ok after a restart
restart-containers ${MASTER} ${LEAF}
memsql-verify-data ${MASTER}

# need to remove the leaf before re-create since its IP might change
remove-leaf ${MASTER} ${LEAF}

# verify the data is a-ok after recreate
delete-containers ${MASTER} ${LEAF}

create-node ${MASTER}
create-node ${LEAF}
wait-start ${MASTER}

# need to just try adding the leaf until it comes up since it can't fully
# recover until it's been added back to the MA
retry add-leaf ${MASTER} ${LEAF}

memsql-verify-data ${MASTER}

echo "success"
