# vim: ft=dockerfile
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY licenses /licenses

# we need to create the memsql user with uid 999 and gid 998 to be compatible with previous centos images
# user-change.sh does this
COPY setup/user-change.sh /
RUN /user-change.sh
RUN rm /user-change.sh

# updates and basic utilities
ARG RELEASE_CHANNEL
RUN rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux
# Tell yum to yell on missing packages.
# https://serverfault.com/a/923357
RUN yum install yum-utils -y
RUN yum-config-manager --save --setopt=skip_missing_names_on_install=0

# currently yum update-minimal fails on curl, so we need to update curl before
RUN yum update curl -y && yum -y update-minimal --setopt=tsflags=nodocs \
      --security --sec-severity=Important --sec-severity=Critical --nobest \
 && yum install -y yum-utils wget procps

RUN yum-config-manager --add-repo https://release.memsql.com/${RELEASE_CHANNEL}/rpm/x86_64/repodata/memsql.repo \
 && yum clean all

RUN dnf --enablerepo=* clean all && dnf update -y

# address vulnarabilities found by `grype --only-fixed` command
RUN yum update expat libxml2 gnupg2 libgcrypt openssl-libs pcre2 curl libcurl-minimal systemd platform-python python3-libs gnutls libksba sqlite-libs zlib libcom_err krb5-libs dbus libtasn1 libarchive unbound-libs tar platform-python-setuptools python3-setuptools-wheel sqlite-libs systemd systemd-libs systemd-pam oniguruma gnutls python3-rpm python3-unbound rpm rpm-build-libs rpm-libs rpm-plugin-systemd-inhibit unbound-libs -y
RUN yum remove vim-minimal platform-python-pip.noarch -y

ARG TOOLBOX_VERSION
ARG KUBE_CLIENT_VERSION

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/${KUBE_CLIENT_VERSION}/bin/linux/amd64/kubectl && \
        chmod +x ./kubectl && \
        mv ./kubectl /usr/local/bin/kubectl

RUN yum install -y \
    singlestoredb-toolbox-${TOOLBOX_VERSION} \
    epel-release \
 && yum clean all

RUN yum update -y \
 && yum clean all && yum remove python3-pip-wheel.noarc -y
