# vim: ft=dockerfile
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG CLIENT_VERSION
RUN yum install -y \
    singlestore-client-${CLIENT_VERSION} \
 && yum clean all

VOLUME ["/var/lib/memsql"]

LABEL name="SingleStore Dynamic Node"
LABEL vendor="SingleStore"
LABEL version=1
LABEL release=1
LABEL summary="The official Docker image for running any version of a single-node SingleStore DB server."
LABEL description="The official Docker image for running any version of a single-node SingleStore DB server."
LABEL io.k8s.display-name="SingleStore DB Dynamic Node"
LABEL io.k8s.description="The official Docker image for running any version of a single-node SingleStore DB server."
LABEL io.openshift.tags="database,db,sql,memsql,singlestore"

EXPOSE 3306/tcp

ADD assets /assets
RUN chmod 555 /assets/startup-exporter

CMD ["/assets/startup-dynamic"]
