# vim: ft=dockerfile
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG TOOLBOX_VERSION
ARG KUBE_CLIENT_VERSION

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/${KUBE_CLIENT_VERSION}/bin/linux/amd64/kubectl && \
        chmod +x ./kubectl && \
        mv ./kubectl /usr/local/bin/kubectl

RUN yum install -y \
    which \
    memsql-toolbox-${TOOLBOX_VERSION} \
    epel-release \
 && yum clean all

RUN yum update -y \
 && yum install -y python-pip python3 \
 && yum clean all

RUN pip install awscli
RUN pip3 install pymysql
RUN pip3 install boto3

ADD assets/report /report
ADD assets/snapshot /snapshot
ADD assets/scripts /scripts
ADD assets/backup /backup
