# vim: ft=dockerfile
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG TOOLBOX_VERSION
ARG KUBE_CLIENT_VERSION

RUN yum install -y \
    which \
    singlestoredb-toolbox-${TOOLBOX_VERSION} \
    epel-release \
 && yum clean all

RUN yum update -y \
 && yum install -y python-pip python3 \
 && yum clean all

RUN pip3 install awscli
RUN pip3 install pymysql
RUN pip3 install boto3

ADD assets/report /report
ADD assets/snapshot /snapshot
ADD assets/scripts /scripts
ADD assets/backup /backup
