# vim: ft=dockerfile
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# install MemSQL packages and additional dependencies
ARG CLIENT_VERSION
ARG SERVER_VERSION
ARG STUDIO_VERSION
ARG TOOLBOX_VERSION
RUN yum install -y \
    memsql-client-${CLIENT_VERSION} \
    memsql-server${SERVER_VERSION} \
    memsql-studio-${STUDIO_VERSION} \
    memsql-toolbox-${TOOLBOX_VERSION} \
 && yum clean all

RUN mkdir /home/memsql && chown memsql:memsql /home/memsql
ADD ciab-assets/studio.hcl /var/lib/memsql-studio/studio.hcl
RUN chown memsql:memsql /var/lib/memsql-studio/studio.hcl

VOLUME ["/var/lib/memsql"]

LABEL name="MemSQL Cluster in a Box"
LABEL vendor="MemSQL"
LABEL version=${SERVER_VERSION}
LABEL release=1
LABEL summary="The official docker image for testing MemSQL + Studio (cluster-in-a-box)."
LABEL description="The official docker image for testing MemSQL + Studio.  Check out the tutorial: http://docs.memsql.com/docs/quick-start-with-docker/"
LABEL io.k8s.display-name="MemSQL Cluster in a Box"
LABEL io.k8s.description="The official docker image for testing MemSQL + Studio.  Check out the tutorial: http://docs.memsql.com/docs/quick-start-with-docker/"
LABEL io.openshift.tags="database,db,sql,memsql,testing,studio,dashboard"

EXPOSE 3306/tcp
EXPOSE 3307/tcp
EXPOSE 8080/tcp
USER memsql
WORKDIR "/home/memsql"
ENV PYTHONUNBUFFERED=1

ADD ciab-assets/startup /startup
CMD ["/startup"]
