#!/usr/bin/env bash
set -e

# This script is designed to be run in a Kubernetes init-container running as
# root to initialize certain resources such as the permissions on the
# /var/lib/memsql volume.

# Check to see if /var/lib/memsql has incorrect permissions, if so fix them
if [[ -e /var/lib/memsql && "$(stat -c '%U:%G' /var/lib/memsql)" != "memsql:memsql" ]] ; then
    echo "Changing permissions of /var/lib/memsql to memsql:memsql"

    # Note: For performance reasons - we only adjust the top of the directory tree.
    # For a properly configured SingleStore DB node, all files created after this point will
    # be owned by the memsql user and group so there is no need to manage
    # permissions below the top level.
    chown memsql:memsql /var/lib/memsql
fi
