#!/usr/bin/env bash
set -e

source /assets/lib.sh

if [ -z "${RELEASE_ID}" ]; then
    log "RELEASE_ID must be defined in the environment"
    exit 1
fi

# ensure SingleStore DB is installed
once /opt/.install-lock installRelease "${RELEASE_ID}"

if [ -z "${EXPORTER_STARTUP_SCRIPT}" ]; then
    log "EXPORTER_STARTUP_SCRIPT must be defined in the environment"
    exit 1
fi

if ! [ -x "${EXPORTER_STARTUP_SCRIPT}" ]; then
    log "EXPORTER_STARTUP_SCRIPT is set to a non-executable file"
    exit 1
fi

${EXPORTER_STARTUP_SCRIPT}

